# redis-server.yml
version: '3'
services:
  daphne:
    build: .
    command: sh command.sh
    container_name: daphne
    hostname: root
    volumes:
      - .:/usr/src/app
    ports:
      - 8021:8021
    restart: unless-stopped