# Generated by Django 4.0.2 on 2022-02-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_Order',
            fields=[
                ('trade_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee', models.IntegerField(default=0, verbose_name='수수료')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='수정날짜')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeorder', to='accounts.asset')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
            ],
            options={
                'db_table': 'trade_order',
            },
        ),
        migrations.CreateModel(
            name='Trade_History',
            fields=[
                ('trade_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(verbose_name='거래가격')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('trade_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trade_History', to='trades.trade_order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
            ],
            options={
                'db_table': 'trade_history',
            },
        ),
    ]
