# Generated by Django 4.0.2 on 2022-02-26 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_Order',
            fields=[
                ('trade_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(verbose_name='거래가격')),
                ('reg_amount', models.IntegerField(verbose_name='등록수량')),
                ('cur_amount', models.IntegerField(verbose_name='현재수량')),
                ('fee', models.IntegerField(default=0, verbose_name='수수료')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='수정날짜')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeorder', to='stocks.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeorder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_order',
            },
        ),
        migrations.CreateModel(
            name='Trade_History',
            fields=[
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정날짜')),
                ('trade_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(verbose_name='거래가격')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('trade_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trade_History', to='trades.trade_order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
            ],
            options={
                'db_table': 'trade_history',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trades.trade_order',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trades.trade_order',),
        ),
    ]
