# Generated by Django 4.0.2 on 2022-02-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        ('commons', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Item',
            fields=[
                ('asset_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="asset_item", to='accounts.asset')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('trade_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trades.trade_order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
            ],
            options={
                'db_table': 'asset_item',
            },
        ),
    ]
