# Generated by Django 4.0.2 on 2022-02-18 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from assets.models import *

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('stocks', '0001_initial'),
        ('trades', '0001_initial'),
    ]
    def gen_asset(app,scheme_editor):
        target = [Asset_Item(point=100,code_id=4,type_id=1,user_id=1,product_id=1,trade_order_id=1) for i in range(10)]
        targets = [[Asset_Item(point=50,code_id=5,type_id=2,user_id=2,product_id=1,trade_order_id=j+2) for i in range(10000)] for j in range(4)]
        Asset_Item.objects.bulk_create(target)
        for i in targets:
            Asset_Item.objects.bulk_create(i)
    operations = [
        migrations.CreateModel(
            name='Asset_Item',
            fields=[
                ('asset_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.product')),
                ('trade_order',models.ForeignKey(on_delete=models.DO_NOTHING,null=True,related_name="asset_item", to='trades.trade_order')),
                ('type',models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
                ('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_item', to=settings.AUTH_USER_MODEL))
            ],
            options={
                'db_table': 'asset_item',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True,blank=True,default=0,verbose_name='보유량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet', to='stocks.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.RunPython(gen_asset)
    ]
