# Generated by Django 4.0.2 on 2022-02-15 01:12

from django.conf import settings
from django.db import migrations, models
from market.models import *
from accounts.models import *
from products.models import *
import django.db.models.deletion


class Migration(migrations.Migration):

    def gen_trade_order(App,Scheme_editor):
        assets = Asset.objects.all()
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(verbose_name='수수료',default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='수정날짜')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeorder', to='accounts.asset')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='거래가격')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='게시날짜')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.code')),
                ('tradeorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeitem', to='market.tradeorder')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
