# Generated by Django 4.0.2 on 2022-02-17 18:22

import random
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from accounts.models import *
from assets.models import Asset_Item
from stocks.models import *
from mysite.secret import PASSWORDS
from trades.models import Trade_Order,Seller,Buyer
PASSWORDS = "1234"

def gen_datas():
    print("do i have to gen data?")
    if not User.objects.all().exists():
        print("yes sure")
        def gen_code():
            type = ["BUY","SELL"]
            code = ["NORMAL","COMPLETE","CANCELED","HOLD","MARKET"]
            event = ["SIGNUP","EVENT1"]
            for i in type:
                Type(type=i).save()
            for i in code:
                Code(code=i).save()
            for i in event:
                Event(event=i).save()
        def gen_users():
            User(username="admin",password=make_password(PASSWORDS),email="gksdjf1690@gmail.com",is_superuser=True,is_staff=True).custom_save()
            User(username="test",password=make_password(PASSWORDS),email="test@gmail.com",is_superuser=True,is_staff=True).custom_save()
            for i in range(20):
                User(username=f"test{i}",password=make_password("1234"),email=f"test{i}@gmail.com").custom_save()

            
        def gen_products():
            categories = ["IT","건축","토목","기계","전기","회계","교육","유통","방송","화학","제조","대부"]
            for i in categories:
                Product_Category(name=i).save()
            names = ["삼선중공업","구아바톡","식인펠리컨","배달의만족","카사바마켓"]
            categories = Product_Category.objects.all()
            for name in names:
                Product(name=name,category=random.choice(categories)).save()
        def gen_trade_order():
            for j in range(1,5):
                target =[   Buyer.factory(1,j,50,5000,BUY,HOLD,0),
                        Buyer.factory(2,j,50,5000,BUY,HOLD,0),
                        
                        ]
                for i in target:
                    i.save()
                    i.set_assets()
            
        gen_code()
        gen_users()
        gen_products()
        gen_trade_order()
gen_datas()