# Generated by Django 3.2.12 on 2022-04-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='종목이름')),
            ],
            options={
                'db_table': 'stocks_product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정날짜')),
                ('logged_date', models.DateTimeField(default=None, null=True, verbose_name='로깅날짜')),
                ('name', models.CharField(max_length=20, verbose_name='상품이름')),
                ('start_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일시가')),
                ('end_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일종가')),
                ('max_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='고가')),
                ('min_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='저가')),
                ('product_id', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product_category')),
            ],
            options={
                'db_table': 'stocks_product_log',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정날짜')),
                ('name', models.CharField(max_length=20, verbose_name='상품이름')),
                ('start_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일시가')),
                ('end_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일종가')),
                ('max_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='고가')),
                ('min_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='저가')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product_category')),
            ],
            options={
                'db_table': 'stocks_product',
            },
        ),
    ]
