# Generated by Django 4.0.2 on 2022-02-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='상품이름')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='갱신날짜')),
                ('yester_end_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일종가')),
                ('yester_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일거래량')),
                ('start_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일종가')),
                ('max_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='저가')),
            ],
            options={
                'db_table': 'stocks_product',
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='종목이름')),
            ],
            options={
                'db_table': 'stocks_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product_Log',
            fields=[
                ('product_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20, verbose_name='상품이름')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('yester_end_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일종가')),
                ('yester_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일거래량')),
                ('start_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일종가')),
                ('max_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='저가')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.product')),
            ],
            options={
                'db_table': 'stocks_product_log',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.product_category'),
        ),
    ]
