# Generated by Django 4.0.1 on 2022-02-01 14:13
import random
from django.db import migrations, models
import django.db.models.deletion
from products.models import *
import requests

WORDS = open('products/words.txt',encoding="utf-8").read().splitlines()
already = []
def get_word():
    result = random.choice(WORDS)
    if len(result)<20:
        if result not in already:
            already.append(result)
            return result
    return get_word()

def gen_product_category(x,y):
    PC_LIST = ['제약','금융','제조','무역','IT','전자','건축','설계','연구']
    for i in PC_LIST:
        ProductCategory(name=i).save()
        
def gen_product(x,y):
    categories = ProductCategory.objects.all()
    for i in range(100):
        Product(name = get_word(),category=random.choice(categories),quantity = random.randint(20000,200000),price=random.randint(2000,200000)).save()
    

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='상품이름')),
                ('quantity', models.PositiveIntegerField(verbose_name='총수량')),
                ('price', models.IntegerField(verbose_name='현재가')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='갱신날짜')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='종목이름')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, verbose_name='상품이름')),
                ('quantity', models.PositiveIntegerField(verbose_name='총수량')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.RunPython(gen_product_category),
        migrations.RunPython(gen_product),
    ]
