# Generated by Django 4.0.2 on 2022-02-12 07:12

import random
from unicodedata import category
from django.db import migrations, models
import django.db.models.deletion
from products.models import *

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    def gen_categories(app,scheme_editor):
        categories = ["IT","건축","토목","기계","전기","회계","교육","유통","방송","화학","제조","대부"]
        for i in categories:
            ProductCategory(name=i).save()
    def gen_products(app,scheme_editor):
        names = ["삼선중공업","구아바톡","식인펠리컨"]
        categories = ProductCategory.objects.all()
        for name in names:
            Product(name=name,category=random.choice(categories)).save()

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='상품이름')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='갱신날짜')),
                ('yester_end_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일종가')),
                ('yester_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일거래량')),
                ('start_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일종가')),
                ('max_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='저가')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='종목이름')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, verbose_name='상품이름')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('yester_end_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일종가')),
                ('yester_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='전일거래량')),
                ('start_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='당일종가')),
                ('max_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='저가')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.RunPython(gen_categories),
        migrations.RunPython(gen_products)
    ]
